### ISSUE TITLE
No option to install to Visual Studio 2017

### ISSUE THREAD

**Issue by xmendoza** [arjankuijpers/SpotifyRemote#5] opened 2017-05-18 15:14 UTC
Installing to Visual Studio 2015 is the only option for me

**Comment by arjankuijpers** [comment] 2017-05-26 02:14
Thanks for your report, will be fixed next update.
Duplicate of:  https://github.com/arjankuijpers/SpotifyRemote/issues/7

**Comment by arjankuijpers** [comment] 2017-07-12 02:28
This issue is fixed. Please let me know if you still have issues installing for Visual Studio 2017.

**Closed by arjankuijpers** 2017-07-12 02:28 UTC
Labels: bug, duplicate
